name: run-tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'wip')"
    strategy:
      fail-fast: true
      matrix:
        php: [8.1,8.2,8.3,8.4]
        laravel: [9.*,10.*,11.*]
        exclude:
            - php: 8.1
              laravel: 11.*
            - php: 8.3
              laravel: 9.*
            - php: 8.4
              laravel: 9.*
            - php: 8.4
              laravel: 10.*

    name: P${{ matrix.php }} - L${{ matrix.laravel }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick, fileinfo
          coverage: none

      - name: Setup problem matchers
        run: |
          echo "::add-matcher::${{ runner.tool_cache }}/php.json"
          echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"

      - name: Install dependencies
        run: |
          composer require "laravel/framework:${{ matrix.laravel }}" --no-interaction --no-update
          composer update --prefer-dist --no-interaction

      - name: Execute tests
        env:
          SAFEBROWSING_GOOGLE_API_KEY: ${{ secrets.SAFEBROWSING_GOOGLE_API_KEY }}
        run: vendor/bin/pest
